// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.entity;

import com.test.entity.LeaveE;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LeaveE_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager LeaveE.entityManager;
    
    public static final EntityManager LeaveE.entityManager() {
        EntityManager em = new LeaveE().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long LeaveE.countLeaveEs() {
        return entityManager().createQuery("SELECT COUNT(o) FROM LeaveE o", Long.class).getSingleResult();
    }
    
    public static List<LeaveE> LeaveE.findAllLeaveEs() {
        return entityManager().createQuery("SELECT o FROM LeaveE o", LeaveE.class).getResultList();
    }
    
    public static LeaveE LeaveE.findLeaveE(Long id_) {
        if (id_ == null) return null;
        return entityManager().find(LeaveE.class, id_);
    }
    
    public static List<LeaveE> LeaveE.findLeaveEEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM LeaveE o", LeaveE.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void LeaveE.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void LeaveE.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            LeaveE attached = LeaveE.findLeaveE(this.id_);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void LeaveE.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void LeaveE.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public LeaveE LeaveE.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        LeaveE merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
