// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.entity;

import com.test.entity.LeaveE;
import java.util.Date;

privileged aspect LeaveE_Roo_JavaBean {
    
    public String LeaveE.getId() {
        return this.id;
    }
    
    public void LeaveE.setId(String id) {
        this.id = id;
    }
    
    public String LeaveE.getName() {
        return this.name;
    }
    
    public void LeaveE.setName(String name) {
        this.name = name;
    }
    
    public String LeaveE.getSeason() {
        return this.season;
    }
    
    public void LeaveE.setSeason(String season) {
        this.season = season;
    }
    
    public Date LeaveE.getDateAtleave() {
        return this.dateAtleave;
    }
    
    public void LeaveE.setDateAtleave(Date dateAtleave) {
        this.dateAtleave = dateAtleave;
    }
    
    public String LeaveE.getApoveBy() {
        return this.apoveBy;
    }
    
    public void LeaveE.setApoveBy(String apoveBy) {
        this.apoveBy = apoveBy;
    }
    
    public Boolean LeaveE.getApove() {
        return this.apove;
    }
    
    public void LeaveE.setApove(Boolean apove) {
        this.apove = apove;
    }
    
}
