// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.entity;

import com.test.entity.LeaveE;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect LeaveE_Roo_Configurable {
    
    declare @type: LeaveE: @Configurable;
    
}
