// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.web;

import com.test.entity.LeaveE;
import com.test.web.ApplicationConversionServiceFactoryBean;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.core.convert.converter.Converter;
import org.springframework.format.FormatterRegistry;

privileged aspect ApplicationConversionServiceFactoryBean_Roo_ConversionService {
    
    declare @type: ApplicationConversionServiceFactoryBean: @Configurable;
    
    public Converter<LeaveE, String> ApplicationConversionServiceFactoryBean.getLeaveEToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.test.entity.LeaveE, java.lang.String>() {
            public String convert(LeaveE leaveE) {
                return new StringBuilder().append(leaveE.getId()).append(" ").append(leaveE.getName()).append(" ").append(leaveE.getSeason()).append(" ").append(leaveE.getDateAtleave()).toString();
            }
        };
    }
    
    public Converter<Long, LeaveE> ApplicationConversionServiceFactoryBean.getIdToLeaveEConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.test.entity.LeaveE>() {
            public com.test.entity.LeaveE convert(java.lang.Long id) {
                return LeaveE.findLeaveE(id);
            }
        };
    }
    
    public Converter<String, LeaveE> ApplicationConversionServiceFactoryBean.getStringToLeaveEConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.test.entity.LeaveE>() {
            public com.test.entity.LeaveE convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), LeaveE.class);
            }
        };
    }
    
    public void ApplicationConversionServiceFactoryBean.installLabelConverters(FormatterRegistry registry) {
        registry.addConverter(getLeaveEToStringConverter());
        registry.addConverter(getIdToLeaveEConverter());
        registry.addConverter(getStringToLeaveEConverter());
    }
    
    public void ApplicationConversionServiceFactoryBean.afterPropertiesSet() {
        super.afterPropertiesSet();
        installLabelConverters(getObject());
    }
    
}
